# Generated by Django 3.2.20 on 2023-09-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_appointment_appointment_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_day',
        ),
    ]
