# Generated by Django 3.2.20 on 2023-09-05 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.IntegerField(choices=[(1, '9:30am - 10:30am'), (2, '11:00am - 12:00pm'), (3, '12:30pm - 13:30pm'), (4, '14:00pm - 15:00pm'), (5, '15:30pm - 16:30pm'), (6, '17:00pm - 18:00pm')], default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
