# Generated by Django 3.2.20 on 2023-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
